### ISSUE TITLE
laptop dead after installing latest apple update

### ISSUE THREAD

**Issue by HsounaZinoubi** [the-braveknight/Lenovo-G50-DSDT-Patch#1]
Hello
my laptop dead after installing latest apple update
no power in laptop it wont start
i buy new one hp pavilion and install Sierra , it work for 4 hours and when installing latest update from apple store same problem happen motherboard brick 
now i have two laptop wont start and no power no fun! Lenovo G50-70 + HP Pavilion 15
what is happen ?

**Comment by the-braveknight** [comment]
No idea, you cannot have bricked your laptops simply by installing the latest macOS update.
The issue must be somewhere else...

Try performing an EC reset.

**Comment by HsounaZinoubi** [comment]
i make EC reset there is no life in lenovo or hp laptop
i am sure it is something related to latest apple update, two laptop brick after downloading update and start installing.
it just shutdown and never come to life again!

**Comment by the-braveknight** [comment]
You probably should take your machine to the nearest repairing service, they should know what your problem is, and why it happened.

I'm perfectly sure it has nothing to do with any update. I've updated my machines here and they're up and running perfectly fine. OS updates do not brick computers, there must be another reason.
